client/urls.py
from django.urls import path
from . import views

app_name = 'client'

urlpatterns = [
    path('doctor/<slug:slug>/', views.client_home_doc, name='client_home_doc'),

    path('booking2/', views.booking2, name='booking2'),
    path('test-ana/', views.test_ana, name='test-ana'),
    path('my-appointments/', views.my_appointments, name='my-appointments'),
    path('booking_success/<slug:slug>/', views.booking_success, name='booking_success'),
    path('loginclient/', views.client_login, name='login'),
    path('client_signup/', views.client_signup, name='client_signup'),
    path('book_slot/<int:slot>/', views.book_slot, name='book_slot'),
    path('delete_slot/<int:slot>/', views.delete_slot, name='delete_slot'),
    path('booking/<slug:slug>/', views.client_home_doc, name='booking'),
    path('update_client_profile/<slug:slug>/', views.update_client_profile, name='update_client_profile'),
]

doctor/urls.py
from django.urls import path 
from . import views


from django.urls import re_path as url

app_name  = 'doctor'


urlpatterns = [
    path('test/<int:id>' , views.show_Specialization_detail , name='show_Specialization_detail'),
    #path('show_slot/', views.show_slot,name='show_slot'),
    path('test/', views.test,name='test'),
    
    path('my-patients/<slug:slug>/', views.doctor_patients,name='my-patients'),


    path('add_slot/', views.add_slot,name='add_slot'),
    
    path('doc_home/', views.doc_home,name='doc_home'),
    
    
    
    #path('doc_home_slot/<str:date>/', views.doc_home_slot,name='doc_home_slot'),
    url(r'^doc_home_slot/(?P<date>\d{4}-\d{2}-\d{2})/$', views.doc_home_slot, name='doc_home_slot'),
    path('client_slot_list', views.client_slot_list, name='client_slot_list'),
    
    
    
    path('doctor-dashboard', views.doctor_dashboard, name='doctor-dashboard'),
    
    
    
    url(r'^delete_slot/(?P<slot>\d+)$', views.delete_slot, name='delete_slot'),
    url(r'^confirm_booking/(?P<slot>\d+)$', views.confirm_booking, name='confirm_booking'),

    url(r'^cancel_booking/(?P<slot>\d+)$', views.cancel_booking, name='cancel_booking'),


    # path('app/' , views.app , name='app')
    path('' , views.doctors_list , name='doctors_list'),
    
    path('search' , views.doctor_search , name='search'),
    path('login/' , views.doctor_login , name='login'),
    path('doctor_signup/' , views.doctor_signup , name='doctor_signup'),
    
    path('complate_doc_date/<slug:slug>' , views.complate_doc_date , name='complate_doc_date'),
    path('compete_success/', views.compete_success,name='compete_success'),
    

    path('logout/' , views.doctor_logout , name='logout'),
    #path('<int:id>/myprofile/delete/' , views.delete_profile , name='profile_delete'),
    path('<slug:slug>/myprofile/' , views.myprofile , name='myprofile'),
    path('<slug:slug>/update_profile/' , views.update_profile , name='update_profile'),
    
    path('outocomplete',views.outocomplete,name='outocomplete'),

    path('<slug:slug>/' , views.doctors_detail , name='doctor_detail'),

]








    #path('index/' , views.doctors_list2 , name='index2'),

project/urls.py
from django.contrib import admin
from django.urls import path, include
from doctor.views import doctors_list

from django.conf import settings
from django.conf.urls.static import static
from doctor.views import doctors_list, index

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),  # تسجيل الدخول / تسجيل الخروج
    path('', index, name="index"),  # الرابط الفاضي يفتح صفحة index

    path('admin/', admin.site.urls),
    path('main/', doctors_list, name="mainpage"),  # الصفحة الرئيسية
    path('doctor/', include(('doctor.urls', 'doctor'), namespace='doctor')),
    path('client/', include(('client.urls', 'client'), namespace='client')),

    path('oauth/', include('social_django.urls', namespace='social')),  # تسجيل دخول فيسبوك أو غيره
]

# ملفات static و media في وضع التطوير
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile_Doctor , Doctor_Image


""" class Signup_Form(UserCreationForm):
    username = forms.CharField(label= 'Username')
    first_name = forms.CharField(label='First name')
    last_name = forms.CharField(label='Last name')
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password' , widget=forms.PasswordInput(), min_length=8)
    password2 = forms.CharField(label='Password2' , widget=forms.PasswordInput(), min_length=8)
    
    
    class Meta:
        model = User
        fields = ('username' , 'first_name' , 'last_name' , 'email' , 'password1' , 'password2')
 """



#doctor_signup
class SignupForm(UserCreationForm):
    username = forms.CharField(label= 'اسم المستخدم')
    first_name = forms.CharField(label='الاسم الاول')
    last_name = forms.CharField(label='الاسم الاخير')
    email = forms.EmailField(label='الايميل')
    password1 = forms.CharField(label='كلمه المرور' , widget=forms.PasswordInput(),min_length=8)
    password2 = forms.CharField(label='تاكيد كلمه المرور' , widget=forms.PasswordInput(),min_length=8)
    class Meta:
        model = User
        fields = ('username' , 'first_name' , 'last_name' , 'email' , 'password1' , 'password2')



class Complate_DocDate_Form(forms.ModelForm):
    class Meta:
        model = Profile_Doctor
        fields = ['name' , 'number_phone', 'specialization' ,'Syndicate']  


#doctor_login
class Login_Form(forms.ModelForm):
    username = forms.CharField(label = 'اسم المستخدم' )
    password = forms.CharField(label = 'كلمه المرور' , widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username' , 'password')
        
        
        
        
#update_doctor_profile
class UserForm(forms.ModelForm):
    first_name = forms.CharField(label='الاسم الاول')
    last_name = forms.CharField(label='الاسم الاخير')
    email = forms.EmailField(label='الايميل')
    class Meta:
        model = User
        fields = ['first_name' , 'last_name' , 'email']
        
        
class ProfileDoctorForm(forms.ModelForm):
    
    class Meta:
        model = Profile_Doctor
        exclude = ['user' , 'active_doctor' , 'Syndicate' , 'google_link' , 'tags' ,'who_i' , 'specialization']        
        
        
""" class Doctor_Image_form(forms.ModelForm):
    class Meta:
        model = Doctor_Image
        exclude = ['doctor']  """       
    

doctor/views.py
from django.http import JsonResponse
from django.shortcuts import render , redirect
from django.urls import reverse
from .models import Profile_Doctor , Doctor_Image , Schedule , Specialization
from .forms import Login_Form , SignupForm , UserForm , ProfileDoctorForm  , Complate_DocDate_Form
from django.contrib.auth.models import User 
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from datetime import date as dt, datetime
from .filters import DoctorFilter

from django.db.models.aggregates import Max , Min , Avg , Count , Sum

#from django.http import HttpResponseRedirect, HttpResponse


# Create your views here.

""" def doctors_list2(request):
    doctors = User.objects.all()
    return render(request , 'users/index.html.html' , context={'doctors':doctors,})  """  
# doctor/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'doctor/index.html')

def welcome(request):
    return render(request,'doctor/doctors_list.html', context={})

    
def doctors_list(request):
    doctors = User.objects.all()
    specializations = Specialization.objects.all()

    return render(request , 'doctor/doctors_list.html' , context={'doctors':doctors,'specializations':specializations,})



def doctor_search(request):
    doctors = Profile_Doctor.objects.all()
    myfilter = DoctorFilter(request.GET,queryset=doctors)
    doctors = myfilter.qs

    return render(request , 'doctor/search.html' , context={'doctors':doctors , 'myfilter':myfilter,})

def doctor_patients(request,slug):
    doc = Profile_Doctor.objects.get(user=request.user)    

    schedule = Schedule.objects.filter(doc=doc)

    return render(request,'doctor/my-patients.html', context={ 'schedules':schedule,'doc':doc,})



def doctors_detail(request , slug):
    doctors_detail = Profile_Doctor.objects.get(slug = slug)
    return render(request , 'doctor/doctor-profile.html' , context={'doctors_detail':doctors_detail,})


@login_required
def myprofile(request,slug):
    return render(request , 'doctor/doctor-myprofile.html' , context={})


""" def show_Specialization(request):
    schedules = Schedule.objects.all()
    doc = Profile_Doctor.objects.get(user=request.user)    
    schedules = Schedule.objects.filter(doc=doc)
    return render(request , 'doctor/slot.html' , context={'schedules':schedules})
 """

def show_Specialization_detail(request,id):
    specializations = Specialization.objects.all()
    doc_specialization = Profile_Doctor.objects.filter(specialization=id)    
    return render(request , 'doctor/favourites.html' , context={'doc_specialization':doc_specialization , 'specializations':specializations,})


def doctor_signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username , password = password)
            login(request , user)
            doctor_profile = Profile_Doctor.objects.get(user = request.user)
            return redirect(reverse('doctor:complate_doc_date' , kwargs={'slug': doctor_profile.slug}))
    else:
        form = SignupForm()
        

    return render(request , 'doctor/doctor-register.html' , context={'form':form})


def doctor_login(request):
    if request.method == 'POST':
        form = Login_Form
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request , username=username , password=password)
        if user is not None :
            login(request , user)
            return redirect('doctor:doctors_list')
        else:
            messages.warning(request, "Username or password is incorrect. please try again")
    else:
        form  = Login_Form()
    return render(request , 'doctor/doctor_login.html' , context={'form':form})




@login_required
def update_profile(request ,  slug):
    doctor_profile = Profile_Doctor.objects.get(user = request.user)
    
    if request.method=='POST':
        userform = UserForm(request.POST , instance=request.user)
        doctor_profileform = ProfileDoctorForm(request.POST , request.FILES , instance=doctor_profile)
        if userform.is_valid() and doctor_profileform.is_valid():
            userform.save()
            mydoctor_profileform = doctor_profileform.save(commit=False)
            mydoctor_profileform.user = request.user
            mydoctor_profileform.save()
            return redirect(reverse('doctor:update_profile' , kwargs={'slug': doctor_profile.slug}))
    else:
        userform = UserForm(instance=request.user)
        doctor_profileform = ProfileDoctorForm(instance=doctor_profile)
    return render(request , 'doctor/doctor-profile-settings.html' , {'userform':userform ,'doctor_profileform':doctor_profileform })



@login_required
def doctor_logout(request):
    logout(request)
    return redirect(reverse('doctor:doctors_list'))



@login_required
def doc_home(request):
    doc = Profile_Doctor.objects.get(user=request.user)
    schedule = Schedule.objects.filter(doc=doc)
    for sc in schedule:
        if sc.date < dt.today() :
            sc.delete()
    schedule = Schedule.objects.filter(doc=doc)
    dates = sorted(set([sc.date for sc in schedule]))
    today = Schedule.objects.filter(doc=doc, date=dt.today())
    return render(request,'doctor/schedule-timings.html', context={'doc':doc, 'dates':dates, 'today':today})





@login_required
def add_slot(request):
    if request.method == 'POST':
        doc = Profile_Doctor.objects.get(user=request.user)
        date = request.POST.get('date')
        start = request.POST.get('start')
        no_hours = int(request.POST.get('no_hours'))
        start =  str(datetime.strptime(str(int(start[:2])) +":"+ start[3:],"%H:%M"))[11:16]
        sc = Schedule(doc=doc, date=date, start_time=start, taken=None)
        sc.save()
        for _ in range(no_hours-1):
            start =  str(datetime.strptime(str(int(start[:2])+1) +":"+ start[3:],"%H:%M"))[11:16]
            sc = Schedule(doc=doc, date=date, start_time=start, taken=None)
            sc.save()
    return render(request,'doctor/schedule-timings.html', context={})
    
    

@login_required
def doc_home_slot(request, date):
    doc = Profile_Doctor.objects.get(user=request.user)    
    schedule = Schedule.objects.filter(doc=doc)
    for sc in schedule:
        if sc.date < dt.today() :
            sc.delete()
    schedule = Schedule.objects.filter(doc=doc)
    dates = sorted(set([sc.date for sc in schedule]))
    slot = Schedule.objects.filter(doc=doc, date=date)
    today = Schedule.objects.filter(doc=doc, date=dt.today())
    t = str(dt.today())
    return render(request,'doctor/schedule-timings.html', context={'schedules':schedule,'t':t, 'doc':doc, 'dates':dates, 'slots':slot, 'date':date, 'today':today})


@login_required
def client_slot_list(request):
    doc = Profile_Doctor.objects.get(user=request.user)    
    schedule = Schedule.objects.filter(doc=doc)
    for sc in schedule:
        if sc.date < dt.today() :
            sc.delete()
    schedule = Schedule.objects.filter(doc=doc)
    dates = sorted(set([sc.date for sc in schedule]))
    slot = Schedule.objects.filter(doc=doc)
    today = Schedule.objects.filter(doc=doc, date=dt.today())
    t = str(dt.today())
    return render(request,'doctor/appointments.html', context={'schedules':schedule,'t':t, 'doc':doc, 'dates':dates, 'slots':slot, 'today':today})

@login_required
def doctor_dashboard(request):
    doc = Profile_Doctor.objects.get(user=request.user)    
    schedule = Schedule.objects.filter(doc=doc)
    for sc in schedule:
        if sc.date < dt.today() :
            sc.delete()
    schedule = Schedule.objects.filter(doc=doc)
    dates = sorted(set([sc.date for sc in schedule]))
    slot = Schedule.objects.filter(doc=doc)
    today = Schedule.objects.filter(doc=doc, date=dt.today())
    t = str(dt.today())
    
    slot_today_count= Schedule.objects.filter(doc=doc, date=dt.today()).count
    client_today_slot_count= Schedule.objects.filter(doc=doc ,confirmed=True , date=dt.today()).count
    client_all_slot_count= Schedule.objects.filter(doc=doc  ,confirmed=True).count
    return render(request,'doctor/doctor-dashboard.html', context={'client_all_slot_count':client_all_slot_count ,'client_today_slot_count':client_today_slot_count,'slot_today_count':slot_today_count, 'schedules':schedule,'t':t, 'doc':doc, 'dates':dates, 'slots':slot, 'today':today})





@login_required
def delete_slot(request, slot):
    slot = Schedule.objects.get(id=slot)
    date = slot.date
    slot.delete()
    return redirect(reverse('doctor:doc_home_slot', args=(date,)))



@login_required
def confirm_booking(request, slot):
    slot = Schedule.objects.get(id=slot)
    slot.confirmed = True
    slot.save()
    return redirect(reverse('doctor:client_slot_list'))


@login_required
def cancel_booking(request, slot):
    slot = Schedule.objects.get(id=slot)
    slot.confirmed=False
    slot.cancelled = slot.taken
    slot.taken=None
    slot.save()
    return redirect(reverse('doctor:client_slot_list'))




""" def delete_slot(request, slot):
    slot = Schedule.objects.get(id=slot)
    date = slot.date
    slot.delete()
    return HttpResponseRedirect(reverse('doctor:doc_home_slot', args=(date,))) """




def complate_doc_date(request ,  slug):
    doctor_profile = Profile_Doctor.objects.get(user = request.user)
    
    if request.method=='POST':

doctor/templates/doctor/Profile_Sidebar.html
{% load static %}
<div class="col-md-5 col-lg-4 col-xl-3 theiaStickySidebar">

    <!-- Profile Sidebar -->
    <div class="profile-sidebar">
        <div class="widget-profile pro-widget-content">
            <div class="profile-info-widget">
                <a href="#" class="booking-doc-img">
                    {% if user.profile_doctor.image %}
                    <img src="{{user.profile_doctor.image.url}}" alt="User Image">
                    {% else %}
                    <img src="{% static 'assets/img/doctors/Default-Profile_doctor.jpg' %}" alt="User Image">
                    {% endif %}
                </a>
                <div class="profile-det-info">
                    <h3>Dr. {{user.profile_doctor.user.first_name}} {{user.profile_doctor.user.last_name}}</h3>

                    <div class="patient-details">
                        <h5 class="mb-0">{{user.profile_doctor.specialist_doctor}}</h5>
                    </div>
                </div>
            </div>
        </div>


        <div class="dashboard-widget">
            <nav class="dashboard-menu">
                <ul>
                    <li>
                        <a href="{% url 'doctor:doctor-dashboard' %}">
                            <i class="fas fa-columns"></i>
                            <span>لوحه التحكم</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'doctor:client_slot_list' %}">
                            <i class="fas fa-calendar-check"></i>
                            <span>جدول المواعيد</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'doctor:my-patients' user.profile_doctor.slug %}">
                            <i class="fas fa-user-injured"></i>
                            <span>المرضي</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'doctor:doc_home' %}">
                            <i class="fas fa-hourglass-start"></i>
                            <span> المواعيد المتاحة</span>
                        </a>
                    </li>
{% comment %}                     <li>
                        <a href="reviews.html">
                            <i class="fas fa-star"></i>
                            <span>اراء</span>
                        </a>
                    </li> {% endcomment %}

                    <li>
                        <a href="{% url 'doctor:update_profile' user.profile_doctor.slug %}">
                            <i class="fas fa-user-cog"></i>
                            <span>اعدادات الملف الشخصي</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'password_change' %}">
                            <i class="fas fa-lock"></i>
                            <span>تغيير كلمه المرور</span>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'doctor:logout' %}">
                            <i class="fas fa-sign-out-alt"></i>
                            <span>تسجيل الخروج</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
    <!-- /Profile Sidebar -->
</div>

doctor/templates/doctor/schedule-timings_delete.html
{% extends 'base.html' %}
{% block body %}
{% block chedule_head %}


{% endblock chedule_head %}


<form action="{% url 'doctor:add_slot' %}" method="post">

	<!-- Breadcrumb -->
	<div class="breadcrumb-bar">
		<div class="container-fluid">
			<div class="row align-items-center">
				<div class="col-md-12 col-12">
					<nav aria-label="breadcrumb" class="page-breadcrumb">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
							<li class="breadcrumb-item active" aria-current="page">Schedule Timings</li>
						</ol>
					</nav>
					<h2 class="breadcrumb-title">Schedule Timings</h2>
				</div>
			</div>
		</div>
	</div>

	<!-- /Breadcrumb -->

	<!-- Page Content -->
	<div class="content">
		<div class="container-fluid">

			<div class="row">
				{% include 'doctor/Profile_Sidebar.html' %}


				<div class="col-md-7 col-lg-8 col-xl-9">

					<div class="row">
						<div class="col-sm-12">
							<div class="card">
								<div class="card-body">
									<h4 class="card-title">Schedule Timings</h4>
									<div class="profile-box">
										<div class="row">
											<form action="{% url 'doctor:add_slot' %}" method="post">
												{% csrf_token %}
												<input type="date" name="date" id="date" class="form-control"
													min="{{t}}">
												<input type="time" name="start" id="time" class="form-control">
												<input type="number" name="no_hours" id="" class="form-control"
													placeholder="Number of hours available"> <br>
												<button class="btn btn-primary btn-block btn-lg login-btn"
													type="submit">Add an appointment</button>
											</form>



											<h1>===================================</h1>

											<!-- Schedule Nav -->
											<div class="schedule-nav">
												<ul class="nav nav-tabs nav-justified">
													{% if date %} {{date}} {% else%} choose date to see
													schedules{% endif %}
													{% for s in dates %}
													<li class="nav-item">
														<a class="nav-link"
															href="{% url 'doctor:doc_home_slot' s %}">{{ s|date:"SHORT_DATE_FORMAT" }}</a>
													</li>
													{% empty %}
													No active schedules.
													{% endfor %}
												</ul>
											</div>
											<!-- /Schedule Nav -->



											<!-- Schedule Content -->
											<div class="tab-content schedule-cont">

												<!-- Sunday Slot -->
												<div id="slot_sunday" class="tab-pane fade">
													<h4 class="card-title d-flex justify-content-between">
														<span>Time Slots</span>
														<a class="edit-link" data-toggle="modal"
															href="#add_time_slot"><i class="fa fa-plus-circle"></i> Add
															Slot</a>
													</h4>
													<p class="text-muted mb-0">Not Available</p>
												</div>
												<!-- /Sunday Slot -->

												<!-- Monday Slot -->
												<div id="slot_monday" class="tab-pane fade show active">
													<h4 class="card-title d-flex justify-content-between">
														<span>Time Slots</span>
														<a class="edit-link" data-toggle="modal"
															href="#edit_time_slot"><i
																class="fa fa-edit mr-1"></i>Edit</a>
													</h4>

													<!-- Slot List -->
													<div class="doc-times">
														{% for slot in slots %}

														<div class="doc-slot-list">
															{{slot.start_time}}
															<a href="{% url 'doctor:delete_slot' slot.id %}"
																class="delete_schedule">
																<i class="fa fa-times"></i>
															</a>
														</div>
														{% endfor %}


														<h1>==================</h2>
	

													{% comment %} 	{% for slot in slots %} {% endcomment %}

{% comment %} 														{% if slot.taken %}{% if slot.confirmed %}

															<b>{{slot.start_time}} </b></li>
														</a>
														{% else %}<a data-bs-toggle="modal" data-bs-target="#confirm{{forloop.counter}}">
														  <li class="list-group-item text-center" style="background-color: rgb(223, 247, 192);">
															<b>{{slot.start_time}} &nbsp;<span class="badge rounded-pill text-bg-warning">Verify and
																confirm</span></b></li>
														</a>
														{% endif %}{% else %}<li class="list-group-item text-center"
														  style="background-color: rgb(192, 218, 247);"><b>{{slot.start_time}} &nbsp;<span
															  class="badge rounded-pill text-bg-info">Empty</span></b>
														  <a data-bs-toggle="modal" data-bs-target="#delete{{forloop.counter}}"><span
															  class="badge bg-danger rounded-pill"><i class="bi bi-trash-fill"></i></span></a></li>
														{% endif %} {% endcomment %}
										  
										  
										  
{% comment %} 														<!-- Modal - Delete slot-->
														<div class="modal fade" id="delete{{forloop.counter}}" tabindex="-1" aria-labelledby="exampleModalLabel"
														  aria-hidden="true">
														  <div class="modal-dialog">
															<div class="modal-content">
															  <div class="modal-header">
																<h1 class="modal-title fs-5" id="exampleModalLabel">Confirm slot</h1>
																<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
															  </div>
															  <div class="modal-body">
																Date and time : {{slot.date}} - {{slot.start_time}} <br>
																Confirm delete ?
															  </div>
															  <div class="modal-footer">
																<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
																<a class="btn btn-primary" href="{% url 'doctor:delete_slot' slot.id %}">Confirm</a>
															  </div>
															</div>
														  </div>
														</div>
										  
														<!-- Modal - Details of slot-->
														<div class="modal fade" id="taken{{forloop.counter}}" tabindex="-1" aria-labelledby="exampleModalLabel"
														  aria-hidden="true">
														  <div class="modal-dialog">
															<div class="modal-content">
															  <div class="modal-header">
																<h1 class="modal-title fs-5" id="exampleModalLabel">Confirm slot</h1>
																<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
															  </div>
															  <div class="modal-body">
																Date and time : {{slot.date}} - {{slot.start_time}} <br>
																Name: {{slot.taken.user.first_name}} {{slot.taken.user.last_name}} <br>
																Place: {{slot.taken.place}} <br>
																Age: {{slot.taken.age}} <br>
																Health history: {{slot.taken.health_history}}
															  </div>
															  <div class="modal-footer">
																<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
															  </div>
															</div>
														  </div>
														</div> {% endcomment %}
										  
														<!-- Modal - Confirm slot-->
	{% comment %} 													Date and time : {{slot.date}} - {{slot.start_time}} <br>
														Name: {{slot.taken.user.first_name}} {{slot.taken.user.last_name}} <br>

														<br><br>
														<b> Confirm booking?</b>
													  </div>
													  <div class="modal-footer">
														<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
														<a class="btn btn-danger" href="{% url 'doctor:cancel_booking' slot.id %}">Cancel</a>
														<a class="btn btn-primary" href="{% url 'doctor:confirm_booking' slot.id %}">Confirm</a>
										  

														
														{% endfor %}
													  </div> {% endcomment %}





														<h1>==================</h2>

													</div>
													<!-- /Slot List -->

												</div>
												<!-- /Monday Slot -->

												<!-- Tuesday Slot -->
												<div id="slot_tuesday" class="tab-pane fade">
													<h4 class="card-title d-flex justify-content-between">
														<span>Time Slots</span>
														<a class="edit-link" data-toggle="modal"
															href="#add_time_slot"><i class="fa fa-plus-circle"></i> Add
															Slot</a>
													</h4>
													<p class="text-muted mb-0">Not Available</p>
												</div>
												<!-- /Tuesday Slot -->

												<!-- Wednesday Slot -->
												<div id="slot_wednesday" class="tab-pane fade">
													<h4 class="card-title d-flex justify-content-between">
														<span>Time Slots</span>
														<a class="edit-link" data-toggle="modal"
															href="#add_time_slot"><i class="fa fa-plus-circle"></i> Add
															Slot</a>
													</h4>
													<p class="text-muted mb-0">Not Available</p>
												</div>
												<!-- /Wednesday Slot -->

												<!-- Thursday Slot -->
												<div id="slot_thursday" class="tab-pane fade">
													<h4 class="card-title d-flex justify-content-between">
														<span>Time Slots</span>
														<a class="edit-link" data-toggle="modal"
															href="#add_time_slot"><i class="fa fa-plus-circle"></i> Add
															Slot</a>
													</h4>
													<p class="text-muted mb-0">Not Available</p>
												</div>
												<!-- /Thursday Slot -->

												<!-- Friday Slot -->
												<div id="slot_friday" class="tab-pane fade">
													<h4 class="card-title d-flex justify-content-between">
														<span>Time Slots</span>
														<a class="edit-link" data-toggle="modal"
															href="#add_time_slot"><i class="fa fa-plus-circle"></i> Add
															Slot</a>
													</h4>
													<p class="text-muted mb-0">Not Available</p>
												</div>
												<!-- /Friday Slot -->

												<!-- Saturday Slot -->
												<div id="slot_saturday" class="tab-pane fade">
													<h4 class="card-title d-flex justify-content-between">
														<span>Time Slots</span>
														<a class="edit-link" data-toggle="modal"
															href="#add_time_slot"><i class="fa fa-plus-circle"></i> Add
															Slot</a>
													</h4>
													<p class="text-muted mb-0">Not Available</p>
												</div>
												<!-- /Saturday Slot -->

											</div>
											<!-- /Schedule Content -->







											====================================

										</div>

									</div>
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>

		</div>

	</div>
	<!-- /Page Content -->





	{% block schedule_footer %}

	{% endblock schedule_footer %}
	{% endblock body %}